#!/bin/bash
# Source OpenFOAM environment (ajustar según la instalación)
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Generar la malla
runApplication blockMesh

# Copiar condiciones iniciales
# cp -r 0.orig 0
restore0Dir

# Configurar regiones con topoSet
runApplication topoSet

# Asignar campos iniciales
runApplication setFields

echo "Ejecución completada."